apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260512-145122-q6cv537b2ca1-service
spec:
  selector:
    app: enterprise-system-20260512-145122-q6cv537b2ca1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
